(function($){var iba_timer=null;var iba_counter=0;var iba_INSIDE_EDITOR=false;var _safariButtonBar=(window.navigator.standalone?0:44);$.fn.iba_control=function(method){var $this=this;var s={id:0,mode:'',type:'',screen:1,page:0,x:0,y:0,w:0,h:0,style:'display:none;',data:'',icons:new Object};var methods={init:function(o){if(o)$.extend(s,o);s.style='position:absolute;overflow:hidden;left:'+ s.x+'px;top:'+ s.y+'px;width:'+ s.w+'px;height:'+ s.h+'px;'+ s.style;this.data('settings',s);return methods.render.apply(this);},render:function(){switch(s.type){case'label':if(typeof s.data.text!='undefined'&&s.mode!='empty')
$(this).html(unescape(s.data.text));s.style+=';line-height:150%!important;';break;case'title':if(typeof s.data.text!='undefined'&&s.mode!='empty')
$(this).html(unescape(s.data.text));break;case'image':if(typeof s.data.image!='undefined'&&s.mode!='empty')
$(this).html('<img src="'+ s.data.image+'" width="'+ s.w+'" height="'+ s.h+'" />');break;case'button':if(typeof s.data.image!='undefined'&&s.data.image){var img=$('<img src="'+ s.data.image+'" alt="" style="position:absolute;overflow:hidden;left:0px;top:0px;width:'+ s.w+'px;height:'+ s.h+'px;"  />');$(img).appendTo($(this));}
if(typeof s.data.text!='undefined'){var txt=$('<div style="position:absolute;overflow:hidden;left:0px;top:0px;width:'+ s.w+'px;height:'+ s.h+'px;line-height:'+ s.h+'px;">'+ s.data.text+'</div>');$(txt).appendTo($(this));}
if(s.data.directUrl){$('<a href="'+ s.data.directUrl+'" target="_blank" style="position: absolute; left: 0px; top: 0px; display: block; width: '+ s.w+'px; height: '+ s.h+'px; z-index: 10;" />').appendTo(this);}
s.style+=';cursor:pointer;cursor:hand;';break;case'menu':$(this).empty();break;case'menubutton':if(typeof s.data.image!='undefined'&&s.data.image){var img=$('<div class="menu-image" style="text-align:center;line-height:'+ Math.round(s.data.h*0.4)+'px;height:'+ Math.round(s.data.h*0.4)+'px;margin:'+ Math.round(s.data.h*0.1)+'px 0px;"><img src="'+ s.data.image+'" height="'+ Math.round(s.data.h*0.4)+'" alt="" style="display:inline;margin:0px!important;padding:0px!important;border:0px!important;vertical-align:top;" /></div>');$(img).appendTo($(this));}
else{$('<div style="height:'+ Math.round(s.data.h*0.4)+'px;padding:Math.round(s.data.h * 0.1)px;" />').appendTo($(this));}
var txt=$('<div class="menu-text" style="text-align:center;color:#fff;line-height:1.1em;font-weight:normal;font-size:60%;position:absolute;overflow:hidden;width:'+ s.data.w+'px;left:0px;top:'+ Math.round(s.data.h*0.6)+'px" />');$(txt).appendTo($(this));if(typeof s.data.text!='undefined')
$(txt).html(s.data.text);if(s.data.directUrl){$('<a href="'+ s.data.directUrl+'" target="_blank" style="position: absolute; left: 0px; top: 0px; display: block; width: '+ s.data.w+'px; height: '+ s.data.h+'px; z-index: 10;" />').appendTo(this);}
s.style+=';cursor:pointer;cursor:hand;';break;case'static':s.style+=';z-index:1;';break;default:break;}
$(this).attr('style',s.style);return this;}};if(methods[method]){return methods[method].apply(this,Array.prototype.slice.call(arguments,1));}else if(typeof method==='object'||!method){return methods.init.apply(this,arguments);}else{$.error('Method '+ method+' does not exist on jQuery.tooltip');}
return this.each(function(){});}
$.fn.iba_model=function(method){var methods={init:function(o){return this.each(function(){iba_INSIDE_EDITOR=(typeof INSIDE_EDITOR!='undefined'&&INSIDE_EDITOR);var s={id:0,x:0,y:0,w:374,h:720,mode:'',source:'/json.php',loader:{x:0,y:0,w:0,h:0,data:{image:'/media/img/ajax-loader.gif',text:'loading...'},el:null},canvas:{id:0,x:0,y:0,w:0,h:0,style:'',el:null},pseudocanvas:{id:0,x:0,y:0,w:0,h:0,style:'',el:null},screen:{id:0,x:0,y:0,w:0,h:0,style:'',el:null,pos:1},preview:{id:0,x:0,y:0,w:0,h:0,style:'',el:null},menu:{id:0,x:0,y:0,w:0,h:0,el:null,items:new Object,first:0},controls:new Object,icons:{h:0,w:0,images:{'add':'/assets/templates/icons/plus.png','edt':'/assets/templates/icons/edit.png','del':'/assets/templates/icons/remove.png'}},sign:{id:0,x:0,y:0,w:0,h:0,el:null}};if(o)$.extend(s,o);s.id=$(this).attr('id');$(this).data('settings',s);$(this).html('<img src="'+ s.loader.data.image+'" height="'+ s.loader.h+'" width="'+ s.loader.w+'" alt="" /> '+ s.loader.data.text);var req={action:'tmpl-init-model',template:s.id,height:s.h,width:s.w,iswebapp:true};$.getJSON(s.source,req,function(json){if(typeof json.data.model_id=='undefined')
return false;if(json.error){$(this).html(json.error);}else{var model=$('#'+ json.data.model_id);var staticHeight=0;json.data.screen_h-=_safariButtonBar;$(model).attr('style',json.data.model_s+'overflow:hidden;width:'+ json.data.screen_w+'px;height:'+ json.data.screen_h+'px;margin-top:-'+ staticHeight+'px;').css({'background':'none','top':'0px','left':'0px'});var set=$(model).data('settings');set.icons.h=json.data.model_manage_icon_h;set.icons.w=json.data.model_manage_icon_w;set.canvas.y=json.data.screen_y;set.canvas.x=json.data.screen_x;set.canvas.w=json.data.screen_w;set.canvas.h=json.data.screen_h;set.canvas.style=json.data.screen_s;var canvas=$('<div id="canvas-'+ set.id+'" style="'+ set.canvas.style+'" />').css({'position':'relative','overflow':'hidden','top':'0px','left':'0px','width':set.canvas.w+'px','height':set.canvas.h+'px'});set.canvas.el=canvas;set.pseudocanvas.y=json.data.screen_y;set.pseudocanvas.x=json.data.screen_x;set.pseudocanvas.w=json.data.screen_w;set.pseudocanvas.h=json.data.screen_h;var pseudo=$('<div id="pseudocanvas-'+ set.id+'" style="" />').css({'position':'relative','overflow-x':'hidden','overflow-y':'auto','top':'0px','left':'0px','width':set.pseudocanvas.w+'px','height':set.pseudocanvas.h+'px'});set.pseudocanvas.el=pseudo;set.screen.w=json.data.screen_w;set.screen.h=0;var screen=$('<div id="screen-'+ set.id+'" style="display:none;" />').css({'position':'absolute','overflow':'hidden','top':'0px','left':'0px','width':set.screen.w+'px','height':'0px'});set.screen.el=screen;set.loader.w=json.data.screen_w;set.loader.h=json.data.screen_h;var loader=$('<div id="loader-'+ set.id+'" style="display:none;"><img src="'+ s.loader.data.image+'" alt="" />&nbsp;</div>').css({'position':'absolute','overflow':'hidden','top':'0px','left':'0px','width':'0px','height':'0px','text-align':'center'});set.loader.el=loader;if(typeof json.data.sign!=undefined&&json.data.sign){set.sign.el=$('<div id="sign-'+ set.id+'" style="color:#ddd;text-shadow:#000 0 0 0.2em;position:absolute;overflow:hidden;left:0px;bottom:0px;width:'+ set.screen.w+'px;text-align:center;font-style:italic;font-weight:bold;font-size:70%;line-height:140%;vertical-align:top;">'+ json.data.sign+'</div>').appendTo($(pseudo));}
if(typeof json.data.controls=='object'){for(var key in json.data.controls){var control=json.data.controls[key];control.id=key;control.model=set.id;ctrl_id=Math.random()+'';ctrl_id=ctrl_id.replace('.','');if(iba_INSIDE_EDITOR){if(control.type=='image'||control.type=='label'||control.type=='button'){_modelControlsIds[control.type][_modelControlsIds[control.type].length]=ctrl_id;}}
switch(control.type){case'menu':control.y-=_safariButtonBar;var menu=$('<div id="'+ ctrl_id+'" class="'+ control.type+'-'+ set.id+'" />').iba_control(control);set.menu.id=ctrl_id;set.menu.x=control.x;set.menu.y=control.y;set.menu.w=control.w;set.menu.h=control.h;set.menu.el=menu;set.menu.first=control['first-page'];if(typeof control.data.items=='object'){var ml=0;for(var i in control.data.items){var item=control['data'].items[i];ctrl_id=Math.random()+'';ctrl_id=ctrl_id.replace('.','');var item_data={id:i,model:set.id,type:'menubutton',page:item.page,x:ml,y:0,w:item.w,h:item.h,style:item.style,mode:item.mode,data:item,icons:{del:null,add:null,edt:null}};if(json.direct[item.page]){item_data.data.directUrl=json.direct[item.page];}
set.menu.items[ctrl_id]=$('<div id="'+ ctrl_id+'" class="menubutton-'+ json.data.model_id+'" />').iba_control(item_data);ml=ml+ item.w;if(iba_INSIDE_EDITOR){_modelControlsIds.menu[_modelControlsIds.menu.length]=ctrl_id;}}}
break;case'static':break;case'button':if(json.direct[control.page]){control.data.directUrl=json.direct[control.page];}
default:if(typeof control.screen=='undefined')
control.screen=1;if(typeof control.icons=='undefined')
control.icons={del:null,add:null,edt:null};set.controls[ctrl_id]=$('<div id="'+ ctrl_id+'" class="'+ control.type+'-'+ json.data.model_id+' screen-'+ control.screen+'" />').iba_control(control);break;}}
if(iba_INSIDE_EDITOR){_modelControlsIds.ready=true;}}
$(model).data('settings',set).iba_model('render');setTimeout(function(){$('#splashScreen').hide();},5*1000);}});});},next:function(){$(this).iba_model('clear');var set=$(this).data('settings');if(set.screen.pos==1){$(set.screen.el).hide();}else{}
set.screen.pos++;$(this).data('settings',set);if(set.menu.el)
$(set.menu.el).show();$('.manage-control-btn').remove();$('#'+ $(set.pseudocanvas.el).attr('id')+' > .screen-'+ set.screen.pos).each(function(){var ctrl_set=$(this).data('settings');if(ctrl_set.mode!='hidden')
$(this).show();});setTimeout(function(){set.screen.h=($(set.menu.el).is(':visible'))?set.canvas.h- set.menu.h:set.canvas.h;if(navigator.userAgent.toLowerCase().indexOf("android")>-1){set.screen.h=0;}
$(set.screen.el).empty().width(set.screen.w).height(set.screen.h).show();$(this).data('settings',set);$(this).iba_model('mode',set.mode);},200);return this.each(function(){});},prev:function(){$(this).iba_model('clear');var set=$(this).data('settings');if(set.screen.pos>1)
set.screen.pos--;$(this).data('settings',set);setTimeout(function(){if(set.screen.pos==1&&!set.menu.first){$(set.menu.el).hide();}else{$(set.menu.el).show();}
$('.manage-control-btn').remove();$('#'+ $(set.pseudocanvas.el).attr('id')+' > .screen-'+ set.screen.pos).each(function(){var ctrl_set=$(this).data('settings');if(ctrl_set.mode!='hidden')
$(this).show();});set.screen.h=($(set.menu.el).is(':visible'))?set.canvas.h- set.menu.h:set.canvas.h;$(set.screen.el).height(set.screen.h);if(set.screen.pos==1){}else{$(set.screen.el).show('slide',{direction:'right'},200);}
$(set.sign.el).show();$(this).data('settings',set);$(this).iba_model('mode',set.mode);},200);return this.each(function(){});},clear:function(){var set=$(this).data('settings');$('#'+ $(set.pseudocanvas.el).attr('id')+' > div').hide();$('#'+ $(set.pseudocanvas.el).attr('id')+' > div.static-'+ set.id).show();return this.each(function(){});},loader:function(){var set=$(this).data('settings');$(set.loader.el).height(set.screen.h).width(set.screen.w).attr('style','text-align:center;line-height:'+ set.screen.h+'px').appendTo($(set.screen.el));$(this).data('settings',set);return this.each(function(){});},mode:function(value){var set=$(this).data('settings');set.mode=value;$('.manage-control-btn').remove();$('#change-background-link').remove();for(var c in set.controls){if(set.controls[c].type=='button'||set.controls[c].type=='menubutton')
$(set.controls[c]).css('cursor','pointer').unbind('click').bind('click',methods.action);}
if(set.menu.el&&$(set.menu.el).is(':visible')){for(var i in set.menu.items){$(set.menu.items[i]).css('cursor','pointer').unbind('click').bind('click',methods.action);}}
switch(set.mode){case'manage':if(!set.menu.el&&set.screen.pos>1){set.screen.pos=1;$(this).iba_model('prev');}
$(set.screen.el).empty();$('<div />').html('Manage Content').css({'color':'#999','line-height':set.screen.h+'px','text-align':'center','font-size':'120%','font-weight':'bold'}).appendTo($(set.screen.el));var bg=$('<div id="change-background-link" style="position:absolute;overflow:hidden;width:'+ $(this).width()+'px;text-align:center;left:0px;top:'+(set.canvas.h+ set.canvas.y+ 1)+'px"><img src="/media/img/edit.gif" alt="" />').appendTo($(this));$('<a href="javascript:void(0);">CHANGE BACKGROUND</a>').appendTo(bg).click(function(){if(!iba_timer){iba_counter=0;iba_timer=setInterval(function(){iba_counter++;if(iba_counter>100){clearInterval(iba_timer);iba_timer=null;}
return false;},100);var req={action:'tmpl-set-background',template:set.id};$.getJSON(set.source,req,function(json){clearInterval(iba_timer);iba_timer=null;if(json.error){alert(json.error);}else{$.fn.ceebox.overlay();$.fn.ceebox.popup(json.data.html,{width:650,height:575});}});}});var cmi_s='position:absolute;overflow:hidden;text-align:center;cursor:pointer;cursor:hand;display:none;z-index:10';var imi_s='display:inline;margin:0px!important;padding:0px!important;border:0px!important;vertical-align:top;';for(var c in set.controls){var ctrl_id=c;var control=set.controls[c];var ctrl_set=$(control).data('settings');if(!ctrl_set)
continue;if(set.screen.pos==ctrl_set.screen){var cmi_w=set.icons.w;var cmi_h=set.icons.h;var cmi_t=ctrl_set.y- Math.round(cmi_h/2);var cmi_l=Math.round(ctrl_set.x+ ctrl_set.w- cmi_w/2);if(cmi_l+ cmi_h>set.screen.w)
cmi_l=Math.round(set.screen.w- cmi_h)
cmi_t=Math.round(ctrl_set.y+ ctrl_set.h/2- cmi_h- cmi_h*0.2);var btn_a=$('<div class="manage-control-btn" id="add-'+ ctrl_id+'" style="width:'+ cmi_w+'px;height:'+ cmi_h+'px;left:'+ cmi_l+'px;top:'+ cmi_t+'px;'+ cmi_s+'" />').attr('title','<p>Restore '+ ctrl_set.type+'</p>').html('<img src="'+ set.icons.images.add+'" height="'+ cmi_h+'" width="'+ cmi_w+'" style="'+ imi_s+'" />').appendTo($(set.canvas.el));var btn_d=$('<div class="manage-control-btn" id="del-'+ ctrl_id+'" style="width:'+ cmi_w+'px;height:'+ cmi_h+'px;left:'+ cmi_l+'px;top:'+ cmi_t+'px;'+ cmi_s+'" />').attr('title','<p>Remove '+ ctrl_set.type+'</p>').html('<img src="'+ set.icons.images.del+'" height="'+ cmi_h+'" width="'+ cmi_w+'" style="'+ imi_s+'" />').appendTo($(set.canvas.el));var btn_e=$('<div class="manage-control-btn" id="edt-'+ ctrl_id+'" style="width:'+ cmi_w+'px;height:'+ cmi_h+'px;left:'+ cmi_l+'px;top:'+ Math.round(cmi_t+ cmi_h+ cmi_h*0.2)+'px;'+ cmi_s+'" />').attr('title','<p>Edit '+ ctrl_set.type+'</p>').html('<img src="'+ set.icons.images.edt+'" height="'+ cmi_h+'" width="'+ cmi_w+'" style="'+ imi_s+'" />').appendTo($(set.canvas.el));if(ctrl_set.mode=='hidden'){$(btn_a).show();$(btn_d).hide();$(btn_e).hide();}else{$(btn_a).hide();$(btn_d).show();$(btn_e).show();}}}
if(set.menu.el&&$(set.menu.el).is(':visible')){for(var i in set.menu.items){var ctrl_id=i;var item=set.menu.items[i];var item_set=$(item).data('settings');var cmi_w=set.icons.w;var cmi_h=set.icons.h;var cmi_t=item_set.y- Math.round(cmi_h/2);var cmi_l=Math.round(item_set.x+ item_set.w- cmi_w/2);if(cmi_l+ cmi_h>set.screen.w)
cmi_l=Math.round(set.screen.w- cmi_h)
cmi_t=Math.round(set.menu.y+ item_set.h/2- cmi_h- cmi_h*0.2);var btn_a=$('<div class="manage-control-btn" id="add-'+ ctrl_id+'" style="width:'+ cmi_w+'px;height:'+ cmi_h+'px;left:'+ cmi_l+'px;top:'+ cmi_t+'px;'+ cmi_s+'" />').attr('title','<p>Restore menu</p>').html('<img src="'+ set.icons.images.add+'" height="'+ cmi_h+'" width="'+ cmi_w+'" style="'+ imi_s+'" />').appendTo($(set.canvas.el));var btn_d=$('<div class="manage-control-btn" id="del-'+ ctrl_id+'" style="width:'+ cmi_w+'px;height:'+ cmi_h+'px;left:'+ cmi_l+'px;top:'+ cmi_t+'px;'+ cmi_s+'" />').attr('title','<p>Remove menu</p>').html('<img src="'+ set.icons.images.del+'" height="'+ cmi_h+'" width="'+ cmi_w+'" style="'+ imi_s+'" />').appendTo($(set.canvas.el));var btn_e=$('<div class="manage-control-btn" id="edt-'+ ctrl_id+'" style="width:'+ cmi_w+'px;height:'+ cmi_h+'px;left:'+ cmi_l+'px;top:'+ Math.round(cmi_t+ cmi_h+ cmi_h*0.2)+'px;'+ cmi_s+'" />').attr('title','<p>Edit menu</p>').html('<img src="'+ set.icons.images.edt+'" height="'+ cmi_h+'" width="'+ cmi_w+'" style="'+ imi_s+'" />').appendTo($(set.canvas.el));if(item_set.mode=='hidden'){$(btn_a).show();$(btn_d).hide();$(btn_e).hide();}else{$(btn_a).hide();$(btn_d).show();$(btn_e).show();}}}
$('.manage-control-btn').mouseenter(function(){var ctrl_id=$(this).attr('id');ctrl_id=ctrl_id.split('-')[1];$('#'+ ctrl_id).fadeTo(200,0.4);}).mouseleave(function(){var ctrl_id=$(this).attr('id');var type=ctrl_id.split('-')[0];ctrl_id=ctrl_id.split('-')[1];if(type=='add'){$('#'+ ctrl_id).fadeTo(200,0).hide();}else{$('#'+ ctrl_id).fadeTo(200,1);}}).click(function(){var ctrl_id=$(this).attr('id');var type=ctrl_id.split('-')[0];ctrl_id=ctrl_id.split('-')[1];var ctrl_set=$('#'+ ctrl_id).data('settings');var model=$('#'+ ctrl_set.model);var mdl_set=$(model).data('settings');switch(type){case'add':if(!iba_timer){iba_counter=0;iba_timer=setInterval(function(){iba_counter++;if(iba_counter>100){clearInterval(iba_timer);iba_timer=null;}
return false;},100);var req={action:'tmpl-control-restore',template:ctrl_set.model,control:ctrl_set.id,element:ctrl_id,page:ctrl_set.page,type:ctrl_set.type};$.getJSON(mdl_set.source,req,function(json){clearInterval(iba_timer);iba_timer=null;if(json.error){alert(json.error);}else{var tmp_set=$('#'+ ctrl_id).data('settings');tmp_set.mode='';$('#add-'+ ctrl_id).unbind('mouseenter').unbind('mouseleave').hide();$('#edt-'+ ctrl_id).show();$('#del-'+ ctrl_id).show().mouseenter(function(){var ctrl_id=$(this).attr('id');ctrl_id=ctrl_id.split('-')[1];$('#'+ ctrl_id).fadeTo(200,0.4);}).mouseleave(function(){var ctrl_id=$(this).attr('id');ctrl_id=ctrl_id.split('-')[1];$('#'+ ctrl_id).fadeTo(200,1);})
$('#'+ ctrl_id).show().fadeTo(0,1).css('cursor','pointer').bind('click',methods.action).data('settings',tmp_set);$('.button-'+ set.id).attr('title','<p>Click the button<br>to edit the content</p>');$('.menubutton-'+ set.id).attr('title','<p>Click the menu<br>to edit the content</p>');}});}
break;case'del':if(!iba_timer){iba_counter=0;iba_timer=setInterval(function(){iba_counter++;if(iba_counter>100){clearInterval(iba_timer);iba_timer=null;}
return false;},100);var req={action:'tmpl-control-delete',template:ctrl_set.model,control:ctrl_set.id,element:ctrl_id,page:ctrl_set.page,type:ctrl_set.type};$.getJSON(mdl_set.source,req,function(json){clearInterval(iba_timer);iba_timer=null;if(json.error){alert(json.error);}else{var tmp_set=$('#'+ ctrl_id).data('settings');tmp_set.mode='hidden';$('#del-'+ ctrl_id).unbind('mouseenter').unbind('mouseleave').hide();$('#edt-'+ ctrl_id).hide();$('#add-'+ ctrl_id).show().mouseenter(function(){var ctrl_id=$(this).attr('id');ctrl_id=ctrl_id.split('-')[1];$('#'+ ctrl_id).fadeTo(200,0.4);}).mouseleave(function(){var ctrl_id=$(this).attr('id');ctrl_id=ctrl_id.split('-')[1];$('#'+ ctrl_id).fadeTo(200,0);});$('#'+ ctrl_id).fadeTo(0,0).hide().unbind('click').css('cursor','default').attr('title','').data('settings',tmp_set);}});}
break;case'edt':if(!iba_timer){iba_counter=0;iba_timer=setInterval(function(){iba_counter++;if(iba_counter>100){clearInterval(iba_timer);iba_timer=null;}
return false;},100);var req={action:'tmpl-control-edit',template:ctrl_set.model,control:ctrl_set.id,element:ctrl_id,page:ctrl_set.page,type:ctrl_set.type};$.getJSON(mdl_set.source,req,function(json){clearInterval(iba_timer);iba_timer=null;if(json.error){alert(json.error);}else{$.fn.ceebox.overlay();$.fn.ceebox.popup(json.data.html,{width:550,height:320});}});}
break;}});$('.button-'+ set.id).attr('title','<p>Click the button<br>to edit the content</p>');$('.menubutton-'+ set.id).attr('title','<p>Click the menu<br>to edit the content</p>');break;case'preview':var set=$(this).data('settings');if(set.screen.pos==1)
$('.menubutton-'+ set.id).css('background-position','0 0');$('.button-'+ set.id).attr('title','');$('.menubutton-'+ set.id).attr('title','');break;default:for(var c in set.controls){$(set.controls[c]).css('cursor','').unbind('click');}
for(var i in set.menu.items){$(set.menu.items[i]).css('cursor','').unbind('click');}
break;}
$(this).data('settings',set);return this.each(function(){});},render:function(){var set=$(this).data('settings');$(this).empty();$(set.canvas.el).appendTo($(this));set.pseudocanvas.h=((set.menu.first)?set.pseudocanvas.h- set.menu.h:set.pseudocanvas.h);$(set.pseudocanvas.el).appendTo($(set.canvas.el)).height(set.pseudocanvas.h);set.screen.h=(set.menu.first)?set.canvas.h- set.menu.h:set.canvas.h;$(set.screen.el).appendTo($(set.pseudocanvas.el)).height(set.screen.h).show();if(set.menu.el){$(set.menu.el).appendTo($(set.canvas.el)).hide();for(var i in set.menu.items){var item=set.menu.items[i]
var item_set=$(item).data('settings');$(item).appendTo($(set.menu.el)).unbind('click').bind('click',methods.action);if(item_set.mode=='hidden')
$(item).hide();}
if(set.menu.first){$(set.menu.el).show();}}
for(var c in set.controls){var control=set.controls[c];var ctrl_set=$(control).data('settings');$(control).appendTo($(set.pseudocanvas.el));if(ctrl_set.type=='button'||ctrl_set.type=='menubutton')
$(control).unbind('click').bind('click',methods.action);if(set.screen.pos==ctrl_set.screen&&ctrl_set.mode!='hidden'){$(control).show();}}
$(this).data('settings',set);$(this).iba_model('mode',set.mode);},action:function(){if(iba_INSIDE_EDITOR){var imOnSamePage=(_currentEditableElement==this);_currentEditableElement=this;}
var ctrl_set=$(this).data('settings');var ctrl_id=$(this).attr('id');var model=$('#'+ ctrl_set.model);var mdl_set=$(model).data('settings');if(ctrl_set.data.directUrl){return;return;}
for(var c in mdl_set.menu.items){var tmp=mdl_set.menu.items[c].data('settings');tmp.isActive=(ctrl_id==c)?1:0;if(tmp.page==ctrl_set.page||tmp.isActive){$(mdl_set.menu.items[c]).css('background-position','0 100%');}else{$(mdl_set.menu.items[c]).css('background-position','0 0');}
mdl_set.menu.items[c].data('settings',tmp);}
switch(mdl_set.mode){case'preview':if(!iba_timer){var iba_loadingAjaxes=(!iba_INSIDE_EDITOR||imOnSamePage?1:2);var iba_counter=0;var iba_timer=setInterval(function(){iba_counter++;if(iba_counter>100){clearInterval(iba_timer);iba_timer=null;}
return false;},100);if(!iba_INSIDE_EDITOR||!imOnSamePage){mdl_set.screen.pos=ctrl_set.screen;$(model).iba_model('next');}
var req={action:'tmpl-control-preview',template:mdl_set.id,control:ctrl_set.id,page:ctrl_set.page,type:ctrl_set.type,iswebapp:true};if(iba_INSIDE_EDITOR){var previewLock=getLock('previewArea');}
$.getJSON(mdl_set.source,req,function(json){if(--iba_loadingAjaxes==0){clearInterval(iba_timer);iba_timer=null;}
if(iba_INSIDE_EDITOR&&!releaseLock('previewArea',previewLock)){return false;}
if(json.error){$(mdl_set.screen.el).html(json.error);}
else{$(mdl_set.screen.el).html(json.data.html);}});if(iba_INSIDE_EDITOR&&!imOnSamePage){$('#'+ mdl_set.target).html('<div style="text-align:center;"><img src="'+ mdl_set.loader.data.image+'" height="22" /> loading...</div>');var req={action:'tmpl-control-form',template:mdl_set.id,control:ctrl_set.id,element:ctrl_id,page:ctrl_set.page,type:ctrl_set.type,func:ctrl_set.func,editor:'iphone'};var editorLock=getLock('editorArea');$.getJSON(mdl_set.source,req,function(json){if(--iba_loadingAjaxes==0){clearInterval(iba_timer);iba_timer=null;}
if(!releaseLock('editorArea',editorLock)){return false;}
$('#'+ mdl_set.target).empty();if(json.error){$('#'+ mdl_set.target).html('<p class="error">'+ json.error+'</p>');}
else{$('#'+ mdl_set.target).html(json.data.html);}});}}
break;case'manage':if(!iba_timer){iba_counter=0;iba_timer=setInterval(function(){iba_counter++;if(iba_counter>100){clearInterval(iba_timer);iba_timer=null;}
return false;},100);$('#'+ mdl_set.target).html('<div style="text-align:center;"><img src="'+ mdl_set.loader.data.image+'" height="22" /> loading...</div>');var req={action:'tmpl-control-form',template:mdl_set.id,control:ctrl_set.id,element:ctrl_id,page:ctrl_set.page,type:ctrl_set.type,func:ctrl_set.func};$.getJSON(mdl_set.source,req,function(json){clearInterval(iba_timer);iba_timer=null;$('#'+ mdl_set.target).empty();if(json.error){$('#'+ mdl_set.target).html('<p class="error">'+ json.error+'</p>');}
else{$('#'+ mdl_set.target).html(json.data.html);}});}
break;}}};if(iba_INSIDE_EDITOR){_iba_methods_action=methods.action;}
if(methods[method]){return methods[method].apply(this,Array.prototype.slice.call(arguments,1));}else if(typeof method==='object'||!method){return methods.init.apply(this,arguments);}else{$.error('Method '+ method+' does not exist on jQuery.tooltip');}};})(jQuery);